language: java
sudo: false
env:
    global:
        #key for github
        #GITHUB_OAUTH_TOKEN
        - secure: "cl88/CyRp6/NUjlFRsyidBgHo3eIqfUQnpmNowSLgdkROdAd4Y71sg9O0j/QOwxGv1AMmbjGLMk4RAqK1Nts10RUy5s+PYGCcHH4hEczzpGlmsAU9du/8KnwHPRZt6NPndMJZDYvHcRMbJ07wrYgnBkMKs3x0i1m05N3XWVPb+3WqqryNuwHW86nV0iJtn7YUfFQYzw0qry+6M5KbCPklGaF9DYaznTrzVf4FpMfAYIkMzowR89HKXCeVIUWKs5zAo09taPHalgXrcBRCqcOdUfJSDwiIIUyP3Uhsz/LKk9etwXROQps/VqTI7mfzzCHyeZvLHvoxxjjh4FV5EHkIFqHDNP8LYRzEsD5J0iIlqt8rMw5VrlUMQADs04GTuESbpgzMNMdE5xNKxPqnbR92lkV8l+Kn5fPtWUQ2HGxr3/aGxXgn8qM+qsdi16NdN6OEm55y/gVP8NOSr6+wFmR9G2YqqTFH+u/oxuMw31TKsJinDH58EA605omOI60yifd07Rda3SLL03OLhUvodI4rs0RbckdyvTdhIdDK6HTE/wDKilattEKOQEKGcgS69A/h2xM7B1dkiLgFVkBkrHmceEIJPvnJhL26kgHYOs4qdyzptl1PftVHI1eV0DnohSVSD5lCp76AnM7T+B+0OraCLYP/d+Ej+nAI/kDMOUhyZo="
        - environment=test
        #sonatype credentials
        #OSSRH_JIRA_USERNAME
        - secure: "UCsH5IT/wpkoy7lsUbG915TNDlICPQnokzvgCKKHSOy7aSk9k9AWYWfwnDWsFTWnM9jTnsYJm1HxseVwcuNf8d2SRGnDhJ7JsfGMcx3ozrNyC+cQNzapem/LFFW8b6EWoVGf2HBa/xVgntthQkKDrvKfWkddVdZj6JmRzWjYY6MdPsvocdPibFGPjC0MMavaAecH3qR1LHKcfDBt0vGOJrIQyDtmRKTPzco0K3+5ehw5ZQPqdJhQX3cTaaaCZSojv573t/5I+D4FBM87RnqBRaGsZlsDJoWMUlebtR4Ojiqf/T9jGP5W88kS8seOkXrkSxoC9l2F8KMGoQ27MhjKOQEATPtvTKUTwWbXpoPkohzQpwm2eLEQ2Ffr3tpPBnRGb0Rszrh7ZqHY1ZMdstDnUlXomxiGYnOOaurMI+owYue2nzDf8jryoQoL2k/B1aK9uiMEzmsQgAv0ddaetAwDJqPYQrYQmT/4OCTSCTpOPWNTfRGMRxHSba6q5OxdO032LKVpls1xXESlxefb/4NCVVPe9sr/KMYgLrXCxXEMVFyxVmCgFvr5iyjF+HEkCZpIlebTlsAGgmITSohIuft+uV2WOvrtOoMSDfKJw+/ulkoLFEjsJSIGpgt9HqQ5cmEaTyIMD/06ytaQ//q6iTzJfNBL3d+RY4SWP4RPf4M5+9k="
        #OSSRH_JIRA_PASSWORD
        - secure: "mioexv5bAYl7HYhLmtPzRzHVlkIvSmx2qwdqsEeq7vaiL6whruvh6deeJcT0q3QhkFWLsm2MzGe6ZwGuXqVm5CYGU4C4Jjq6fDlK5r6ORD26lFwV3MoLCfaLifBbVaBQYF/Q8RnhM19ULPwmeUzFVMvS6SpzKt6LiwHeB03Cxuoi6RkTLE9VRZP7G9pcwBt6nNBdyOMkpLtcUbJUFYOKl10uZ4kJQApyDxU4J7Uv6HQNGH7u5lDEZKh84q8gAgwIVEYCwVCH/U9SkXRQp/VRwij3od4xYfk/i8+aEY1xzXGoUVTgCZx9Vr3n3GkDq1jehx7o1C+sUe+Ap2TxJvriQHjF55shO5pKPAHef/QFXDess5B8gXVbgYj+O3mNmcwNIwf1Hp8BSf+YAVWyFudaJfznKb00w/KGoIj5ju3UA7qxAtgrYvA13p/Oh9efgkiaohrwcQuWoIX6hN/0iQ83ogc95ODTR+JvLDQtXbToUjPrY9iN/VnkQdRnCSNpDIF/Av0J8ckIihlW6iPC4ngWr04BfAzGc9S0tj1ieJD50PW96cwujAo6JD2K8IcSdl8S2M0/iAVSVTDMgSk8FXIiWBcw2BRGOO02Rog9nGvUaO9WzjDG0nyRJrvRjoFRmHaJUZ+2ZJYlsquqGQt0QJnuJ0I/wkxrt7NOCoY6f/p30Rs="
        #signing key
        #GPG_KEY_NAME
        - secure: "HLzLaw67dPqUC7U2aovNmuz/mnYxLcy7wQvEE9dcUaJrbhWG9SdQvo+TrhNPxrCn/tALNLa3qH1+28fBo3gBGa/0qW6PaeGk3cc4F8HJ1xE+mr/iBtx3NxNHaGz9MY4kdicwSqSJzYUP5XM0y2ikzfyBphpeJpksDkprChWfCC91pIvM4EIVBawfrgYlc0oaM/rKm1AJbVW93K79/5S7WHDhTDz6nj7yACymOqdjX8+ZkDT2FdV4z6zYE0TEtZwxxVf21SQqOFHdUeERdcsuDAJxLXWOt7j7q+Mt43Mlsf4mASuUbhCRpSOIIMgqgpqcmVy5c1qGhcrSaKeP1MaVO1GjuCObe9GPZRF8cJdcaxz5zjQw8XsmlG8lVY74I8PAs3ygrGca4m9/0AJyiU5RGm6iKmpdHrqf/4xerEBs6I2r/QSnsNHvELC69f/J/opNVEKCXxDI1FZ7w4QpxEHL7nw44AMyKbSjssKeV5k9gJu7t9et5TudR++2EfItRGfthdDvppRpwOgI4D+rXBYkwxbbd3mJvh32VbZwFIGn4+feWxkhoyBKwdtvgTY6vZ/5SsF7lDRrhjozd5ns5beWe9UqdCav99KW5ci/QL/VzgehlzHwGpG238RZPXjM4wYE0sja4W9R3ai9Iho4JcZGOYCv1CCMeIyBtmQUE+Ng7Kw="
        #GPG_PASSPHRASE
        - secure: "NULp2Uj3TXeWrF3Ee8FuYH0sEj+JFajnF2CCCWwlLjjePFL0NK8saTsG/nktJYdAP3LZI4mrXxfgSwmhGZYrEn4TtwySILSbr1cXYpM5UK2kn+GVx0BFt1akdPMmdlinmHiUn7kKRXxskbo1lbuWI93k1G9Yh1fkZZt8tPc1IkCkpaRfPhjj/WzPC4bL0kgIo3JL+6OrFYHIiO4UkP+kf/74L6DS8sI0Ua1wAEzuPnhqFvYgMMjEHOB6MNWG2/2to7eINYcMBVj2Jqv66+7UYROnVD3naC87rNadjKB7aW4pProT/hJm1ANU/M/lR5Iu3wHs8m1mdFocDBk93mKJanM7wZ658HRpctuhuFpXhJFw3OSVUtP71msSYcEQI2otaM/6THht+jJ/fWkLCYm03kAaGwPvRbG2IRx2UvLhRQupiXLhCw7ZIqaOTkWh9Xjdd+8razmRAKqT5TOjVD7eG+x7JSaNUC/ES7//ff46mHBF5nG3FOdhOeRol/DaWW5mRJRH/4jmZasZXVV40tf+MRxAN1L8mDbiDA1V9ZA+4uDcQXc70DbB4sY5CmYqE6IuyhRyVzh2xvUV4Xk25HK5cz+1MJt8aVwYpixymDqBmpNGsqPoZJBttF3z8wHpR2+KIxAO9jQe8qTD0z1YbFkNZJWAcNLKvHQU0U/zHj6Yw6Y="

addons:
  sonarcloud:
    organization: "albertoirurueta-github"
    token:
      secure: "Xl8UK3/kIot3OTJClAS3LCw2ZFlS/O+EiEvqSVK4xwNlI2IP+3uA+1Fsx8nSgPKe8atdy8tmoNzEojykQ0mGdcGeuRL7Izci/idpjbelmN8bNW5n03HYxNIDkcX37N/EF9kkw6KQvff/tcurDqRO8Vi/hHv6Qy/RSILJ3GJBPtUT4kYsEC12cDCrUbVGdXfSF9+z1L32EEKi1SakWc9sFGTFO+sT3VKeZ3AJYrOk8zuxi1sVe3NPHr5Dr2r62mlbgj42Fb2pEggg0iywRPFvX1gYHpHDXGpUYlRFaIulqXNqF0NJT/3hnqcYBcRQCPWLlHCrs1wpVBlaRhkJ27ekXQswmIeDfhcqBlydKbdyP5sC98IRaAExcDkP7EEJs8ZHyc+/a4kW3HWsWwNffrBYs/dSqlF9qpQfMi9VFc0ozo7OEzTJQhwvJHUat0PFdQDNPUx44Y+9+Dp9Fy8dHuoBElGb05I8FYUy9gDmE+2hm97fe9RMkxD4oBSB1N+txsZNbNsLnemaIGE65HJFzlX0/dLNG7Urh7nGscK21TefwEHcqFfhSxx+7mDklR4Fkvok/6d2iIMCSXMKPHij+MiviTLgO2kddpYZdYG0zx7Plmec7yEqSD8HjpuLGWej2YU7ylr95bWNcfXUxmk6o1xl3/OsX6RlCdmsGZnOulbTmS8="

#if timeout occurs, add travis_wait as in example below:
#script: travis_wait mvn clean jacoco:prepare-agent install jacoco:report site

#add: -Denvironment=test to activate CI profile to publish into gh-pages
script:
  - mvn clean jacoco:prepare-agent install jacoco:report -Denvironment=test -P !build-extras
  - mvn site -Djacoco.skip -DskipTests -P !build-extras
  - sonar-scanner

cache:
  directories:
    - ~/.m2/repository

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_OAUTH_TOKEN
  keep-history: true
  local-dir: ./target/site
  on:
    branch: master

after_success:
  - ./cd/before-deploy.sh
  - ./cd/deploy.sh
